SEED_USERS = [
    {
        "username": "standard_user",
        "password": "secret_sauce",
        "display_name": "Alex Reader",
        "user_type": "standard_user",
    },
    {
        "username": "locked_out_user",
        "password": "secret_sauce",
        "display_name": "Sam Locked",
        "user_type": "locked_out_user",
    },
    {
        "username": "problem_user",
        "password": "secret_sauce",
        "display_name": "Pat Problem",
        "user_type": "problem_user",
    },
    {
        "username": "performance_glitch_user",
        "password": "secret_sauce",
        "display_name": "Chris Slow",
        "user_type": "performance_glitch_user",
    },
    {
        "username": "admin_user",
        "password": "secret_sauce",
        "display_name": "Library Admin",
        "user_type": "admin_user",
    },
]

SEED_BOOKS = [
    # Fiction
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "category": "Fiction",
        "isbn": "978-0-7432-7356-5",
        "year": 1925,
        "description": "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set against the backdrop of the Roaring Twenties.",
        "cover_color": "#E8D5B7",
        "total_copies": 3,
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "category": "Fiction",
        "isbn": "978-0-06-112008-4",
        "year": 1960,
        "description": "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
        "cover_color": "#C5A880",
        "total_copies": 3,
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "category": "Fiction",
        "isbn": "978-0-452-28423-4",
        "year": 1949,
        "description": "A dystopian novel set in a totalitarian society ruled by Big Brother, exploring themes of surveillance and individual freedom.",
        "cover_color": "#2C3E50",
        "total_copies": 3,
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "category": "Fiction",
        "isbn": "978-0-14-143951-8",
        "year": 1813,
        "description": "A romantic novel following Elizabeth Bennet as she navigates issues of manners, upbringing, morality, and marriage in early 19th-century England.",
        "cover_color": "#8E44AD",
        "total_copies": 3,
    },
    # Science
    {
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "category": "Science",
        "isbn": "978-0-553-38016-3",
        "year": 1988,
        "description": "A landmark volume in science writing that explores the origin, structure, development, and eventual fate of the Universe.",
        "cover_color": "#1A252F",
        "total_copies": 3,
    },
    {
        "title": "The Selfish Gene",
        "author": "Richard Dawkins",
        "category": "Science",
        "isbn": "978-0-19-857519-1",
        "year": 1976,
        "description": "A groundbreaking work presenting gene-centered view of evolution, introducing the concept of the 'selfish gene'.",
        "cover_color": "#27AE60",
        "total_copies": 3,
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "category": "Science",
        "isbn": "978-0-06-231609-7",
        "year": 2011,
        "description": "An exploration of the ways in which biology and history have defined us and enhanced our understanding of what it means to be human.",
        "cover_color": "#E74C3C",
        "total_copies": 3,
    },
    # History
    {
        "title": "Guns, Germs, and Steel",
        "author": "Jared Diamond",
        "category": "History",
        "isbn": "978-0-393-31755-8",
        "year": 1997,
        "description": "A survey of human history as shaped by geography and ecology rather than race, explaining why Western civilizations came to dominate the world.",
        "cover_color": "#D4AC0D",
        "total_copies": 3,
    },
    {
        "title": "The Art of War",
        "author": "Sun Tzu",
        "category": "History",
        "isbn": "978-1-59030-259-2",
        "year": -500,
        "description": "An ancient Chinese military treatise attributed to Sun Tzu, covering strategy, tactics, and philosophy still relevant today.",
        "cover_color": "#922B21",
        "total_copies": 3,
    },
    {
        "title": "Longitude",
        "author": "Dava Sobel",
        "category": "History",
        "isbn": "978-0-14-025879-0",
        "year": 1995,
        "description": "The true story of a lone genius who solved the greatest scientific problem of his time — determining longitude at sea.",
        "cover_color": "#1F618D",
        "total_copies": 3,
    },
    # Technology
    {
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "category": "Technology",
        "isbn": "978-0-13-235088-4",
        "year": 2008,
        "description": "A handbook of agile software craftsmanship, providing principles, patterns, and practices for writing clean code.",
        "cover_color": "#17202A",
        "total_copies": 3,
    },
    {
        "title": "The Pragmatic Programmer",
        "author": "David Thomas, Andrew Hunt",
        "category": "Technology",
        "isbn": "978-0-201-61622-4",
        "year": 1999,
        "description": "A guide to becoming a more effective and efficient programmer through a series of practical tips and anecdotes.",
        "cover_color": "#1E8BC3",
        "total_copies": 3,
    },
    {
        "title": "Designing Data-Intensive Applications",
        "author": "Martin Kleppmann",
        "category": "Technology",
        "isbn": "978-1-449-37332-0",
        "year": 2017,
        "description": "A deep dive into the fundamentals of data systems and how to build reliable, scalable, and maintainable applications.",
        "cover_color": "#E67E22",
        "total_copies": 3,
    },
    {
        "title": "The Mythical Man-Month",
        "author": "Frederick P. Brooks Jr.",
        "category": "Technology",
        "isbn": "978-0-201-83595-3",
        "year": 1975,
        "description": "Essays on software engineering and project management, introducing Brooks's Law: adding manpower to a late project makes it later.",
        "cover_color": "#6C3483",
        "total_copies": 3,
    },
    # Biography
    {
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "category": "Biography",
        "isbn": "978-1-4516-4853-9",
        "year": 2011,
        "description": "The biography of Apple's co-founder based on more than forty interviews with Jobs conducted over two years.",
        "cover_color": "#717D7E",
        "total_copies": 3,
    },
    {
        "title": "Leonardo da Vinci",
        "author": "Walter Isaacson",
        "category": "Biography",
        "isbn": "978-1-5011-3915-4",
        "year": 2017,
        "description": "A fascinating biography of the greatest creative genius in history, drawing on his notebooks and new discoveries.",
        "cover_color": "#B7950B",
        "total_copies": 3,
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "category": "Biography",
        "isbn": "978-0-399-59050-4",
        "year": 2018,
        "description": "A memoir about a young girl who grows up in a survivalist family in the mountains of Idaho and goes on to earn a PhD from Cambridge.",
        "cover_color": "#1ABC9C",
        "total_copies": 3,
    },
    # Fantasy
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "category": "Fantasy",
        "isbn": "978-0-547-92822-7",
        "year": 1937,
        "description": "The adventure of Bilbo Baggins, a homebody hobbit who is swept into an epic quest with a group of dwarves and a wizard.",
        "cover_color": "#28B463",
        "total_copies": 3,
    },
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "category": "Fantasy",
        "isbn": "978-0-590-35340-3",
        "year": 1997,
        "description": "The start of the beloved series following Harry Potter as he discovers he's a wizard and enrolls in Hogwarts School of Witchcraft and Wizardry.",
        "cover_color": "#7D3C98",
        "total_copies": 3,
    },
    {
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "category": "Fantasy",
        "isbn": "978-0-7564-0407-9",
        "year": 2007,
        "description": "The first-person narrative of Kvothe, a legendary hero who now lives as a simple innkeeper, telling his life story to a chronicler.",
        "cover_color": "#C0392B",
        "total_copies": 3,
    },
]
